"""
inspiration:
    - https://github.com/T-Dynamos/materialyoucolor-python
    - https://github.com/sudoevolve/material-components-pyside
"""

import typing as t
from functools import partial
from materialyoucolor.dynamiccolor.material_dynamic_colors import \
    MaterialDynamicColors
from materialyoucolor.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot
from qtpy.QtCore import Property
from qtpy.QtGui import QColor
from ..qtcore import QObject
from ..qtcore import Signal

class Color(QObject):

    def __init__(self):
        super().__init__()
        # self._seed_color = QColor('#214E80')  # a blue color
        self._seed_color = QColor('#6750A4')
        argb = _qcolor_to_argb(self._seed_color)
        self._light_scheme = self._generate_scheme(argb, is_dark=False)
        self._dark_scheme = self._generate_scheme(argb, is_dark=True)
        self._current_scheme = self._light_scheme
        self._is_dark_theme = False

    def _generate_scheme(self, argb: int, is_dark: bool) -> t.Dict[str, str]:
        """
        returns: a dict of color hex strings. 
            e.g. {'primary': '#214E80', 'on_primary': '#FFFFFF', ...}
        """
        source = Hct.from_int(argb)
        scheme = SchemeTonalSpot(source, is_dark, 0.0, spec_version='2025')
        colors = MaterialDynamicColors(spec='2025')

        # tokens: 
        #   https://m3.material.io/styles/color/roles
        #   https://m3.material.io/foundations/design-tokens/overview
        out = {}
        for token in (
            'primary',
            'onPrimary',
            'primaryContainer',
            'onPrimaryContainer',
            'secondary',
            'onSecondary',
            'secondaryContainer',
            'onSecondaryContainer',
            'tertiary',
            'onTertiary',
            'tertiaryContainer',
            'onTertiaryContainer',
            'error',
            'onError',
            'errorContainer',
            'onErrorContainer',
            'background',
            'onBackground',
            'surface',
            'onSurface',
            'surfaceVariant',
            'onSurfaceVariant',
            'outline',
            'outlineVariant',
            'shadow',
            'scrim',
            'inverseSurface',
            'inverseOnSurface',
            'inversePrimary',
            'surfaceDim',
            'surfaceBright',
            'surfaceContainerLowest',
            'surfaceContainerLow',
            'surfaceContainer',
            'surfaceContainerHigh',
            'surfaceContainerHighest',
        ):
            # for key using in my program, i'd like the snake_case format.
            key = _camel_to_snake_case(token)
            dyn = getattr(colors, token)
            hex = dyn.get_hex(scheme)  # e.g. '#6750A4FF'
            out[key] = hex[:-2]
        return out

    # --------------------------------------------------------------------------

    def _qget_color(self, name):
        return self._current_scheme[name]

    def _qget_current_scheme(self):
        return self._current_scheme
    
    def _qget_dark_theme(self):
        return self._is_dark_theme

    def _qset_dark_theme(self, is_dark: bool):
        if self._is_dark_theme == is_dark:
            return
        self._is_dark_theme = is_dark
        self._current_scheme = (
            self._dark_scheme if is_dark else self._light_scheme
        )
        self.theme_changed.emit(not self._is_dark_theme)

    theme_changed = Signal(bool)  # Signal[is_light]
    dark_theme = Property(bool, _qget_dark_theme, _qset_dark_theme)

    # below are generated by script `blueprint/make_color_properties.py`.
    primary = Property(
        str,
        partial(_qget_color, name='primary'),
        notify=theme_changed
    )
    on_primary = Property(
        str,
        partial(_qget_color, name='on_primary'),
        notify=theme_changed
    )
    primary_container = Property(
        str,
        partial(_qget_color, name='primary_container'),
        notify=theme_changed
    )
    on_primary_container = Property(
        str,
        partial(_qget_color, name='on_primary_container'),
        notify=theme_changed
    )
    secondary = Property(
        str,
        partial(_qget_color, name='secondary'),
        notify=theme_changed
    )
    on_secondary = Property(
        str,
        partial(_qget_color, name='on_secondary'),
        notify=theme_changed
    )
    secondary_container = Property(
        str,
        partial(_qget_color, name='secondary_container'),
        notify=theme_changed
    )
    on_secondary_container = Property(
        str,
        partial(_qget_color, name='on_secondary_container'),
        notify=theme_changed
    )
    tertiary = Property(
        str,
        partial(_qget_color, name='tertiary'),
        notify=theme_changed
    )
    on_tertiary = Property(
        str,
        partial(_qget_color, name='on_tertiary'),
        notify=theme_changed
    )
    tertiary_container = Property(
        str,
        partial(_qget_color, name='tertiary_container'),
        notify=theme_changed
    )
    on_tertiary_container = Property(
        str,
        partial(_qget_color, name='on_tertiary_container'),
        notify=theme_changed
    )
    error = Property(
        str,
        partial(_qget_color, name='error'),
        notify=theme_changed
    )
    on_error = Property(
        str,
        partial(_qget_color, name='on_error'),
        notify=theme_changed
    )
    error_container = Property(
        str,
        partial(_qget_color, name='error_container'),
        notify=theme_changed
    )
    on_error_container = Property(
        str,
        partial(_qget_color, name='on_error_container'),
        notify=theme_changed
    )
    background = Property(
        str,
        partial(_qget_color, name='background'),
        notify=theme_changed
    )
    on_background = Property(
        str,
        partial(_qget_color, name='on_background'),
        notify=theme_changed
    )
    surface = Property(
        str,
        partial(_qget_color, name='surface'),
        notify=theme_changed
    )
    on_surface = Property(
        str,
        partial(_qget_color, name='on_surface'),
        notify=theme_changed
    )
    surface_variant = Property(
        str,
        partial(_qget_color, name='surface_variant'),
        notify=theme_changed
    )
    on_surface_variant = Property(
        str,
        partial(_qget_color, name='on_surface_variant'),
        notify=theme_changed
    )
    outline = Property(
        str,
        partial(_qget_color, name='outline'),
        notify=theme_changed
    )
    outline_variant = Property(
        str,
        partial(_qget_color, name='outline_variant'),
        notify=theme_changed
    )
    shadow = Property(
        str,
        partial(_qget_color, name='shadow'),
        notify=theme_changed
    )
    scrim = Property(
        str,
        partial(_qget_color, name='scrim'),
        notify=theme_changed
    )
    inverse_surface = Property(
        str,
        partial(_qget_color, name='inverse_surface'),
        notify=theme_changed
    )
    inverse_on_surface = Property(
        str,
        partial(_qget_color, name='inverse_on_surface'),
        notify=theme_changed
    )
    inverse_primary = Property(
        str,
        partial(_qget_color, name='inverse_primary'),
        notify=theme_changed
    )
    surface_dim = Property(
        str,
        partial(_qget_color, name='surface_dim'),
        notify=theme_changed
    )
    surface_bright = Property(
        str,
        partial(_qget_color, name='surface_bright'),
        notify=theme_changed
    )
    surface_container_lowest = Property(
        str,
        partial(_qget_color, name='surface_container_lowest'),
        notify=theme_changed
    )
    surface_container_low = Property(
        str,
        partial(_qget_color, name='surface_container_low'),
        notify=theme_changed
    )
    surface_container = Property(
        str,
        partial(_qget_color, name='surface_container'),
        notify=theme_changed
    )
    surface_container_high = Property(
        str,
        partial(_qget_color, name='surface_container_high'),
        notify=theme_changed
    )
    surface_container_highest = Property(
        str,
        partial(_qget_color, name='surface_container_highest'),
        notify=theme_changed
    )

def _camel_to_snake_case(name: str) -> str:
    return ''.join(('_' + i.lower() if i.isupper() else i for i in name))

def _qcolor_to_argb(color: QColor) -> int:
    return int(color.rgba()) & 0xFFFFFFFF
